/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BankRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.VerificationRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author @author Urvashi
 */
public class VerificationRequestJPanel extends javax.swing.JPanel {
    private JPanel rightContainer;
    private UserAccount userAccount;
    private EcoSystem system;
    
    /**
     * Creates new form VerificationRequestJPanel
     */
    public VerificationRequestJPanel(JPanel rightContainer, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.rightContainer = rightContainer;
        this.system = system;
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblVerifRecords.getModel();
        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization.getOrganizationType().equals(Organization.Type.FundRaisingEvents)) {
                        for (int i = 0; i < organization.getWorkQueue().getWorkRequestList().size(); i++) {
                            VerificationRequest request = (VerificationRequest) organization.getWorkQueue().getWorkRequestList().get(i);
                            Object[] row = new Object[7];
                            row[0] = request.getRequestId();
                            row[1] = request.getUser().getName();
                            row[2] = request.getEvent().getStatus();
                            row[3] = request.getUser().getAccountDetails().getAccountNumber();
                            row[4] = request.getUser().getAccountDetails().getBankName();
                            row[5] = request.getUser().getAccountDetails().getRoutingNumber();
                            row[6] = request.getUser().getAccountDetails().getSWIFTCode();
                            model.addRow(row);
                        }
                    }
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnActionTaken = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVerifRecords = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("VERIFICATION REQUESTS ");

        btnActionTaken.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnActionTaken.setText("Take Action");

        tblVerifRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Number", "User", "Status", "Accuont Number", "Bank Name", "Routing Number", "Swift Code"
            }
        ));
        jScrollPane2.setViewportView(tblVerifRecords);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(btnActionTaken)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnActionTaken)
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActionTaken;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblVerifRecords;
    // End of variables declaration//GEN-END:variables
}
