/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author @author Urvashi
 */
public class CreateNewUser extends javax.swing.JPanel {

    private JPanel leftContainer;
    private JPanel rightContainer;
    private UserAccountDirectory userAccountDirectory;
    
    /**
     * Creates new form CreateNewUser
     */
    public CreateNewUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp = new javax.swing.ButtonGroup();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JRadioButton();
        btnUser = new javax.swing.JRadioButton();
        txtUserName = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        confirmPasswordField = new javax.swing.JPasswordField();

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CREATE USER");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name : ");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("userName : ");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password : ");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Confirm Password : ");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Role : ");

        btnGrp.add(btnAdmin);
        btnAdmin.setText("Admin");

        btnGrp.add(btnUser);
        btnUser.setText("User");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(155, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(52, 52, 52)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCreate)
                    .addComponent(jLabel1)
                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(txtName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdmin)
                        .addGap(18, 18, 18)
                        .addComponent(btnUser))
                    .addComponent(passwordField)
                    .addComponent(confirmPasswordField))
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnAdmin)
                    .addComponent(btnUser))
                .addGap(41, 41, 41)
                .addComponent(btnCreate)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightContainer.remove(this);
        CardLayout leftLayout = (CardLayout) leftContainer.getLayout();
        leftLayout.previous(leftContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String username = txtUserName.getText();
        String pwd = passwordField.getText();
        String rePwd = confirmPasswordField.getText();

        if (username == null || username.equals("")) {
//            txtUserName.setBorder(BorderFactory.createLineBorder(Color.RED));
//            jLabel2.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "UserName cannot be empty");
            return;
        }else{
            //txtUserName.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        }

//        if (!usernamePatternCorrect()) {
//            txtUserName.setBorder(BorderFactory.createLineBorder(Color.RED));
//            jLabel2.setForeground(Color.red);
//            JOptionPane.showMessageDialog(null, "Username should be the form of xxx_xxx@xxx.xxx");
//            return;
//        }else{
//            txtUserName.setBorder(BorderFactory.createLineBorder(Color.BLACK));
//        }
//
//        if (pwd == null || pwd.equals("")) {
//            txtPassword.setBorder(BorderFactory.createLineBorder(Color.RED));
//            jLabel3.setForeground(Color.red);
//            JOptionPane.showMessageDialog(null, "Password cannot be empty");
//            txtPassword.setBorder(BorderFactory.createLineBorder(Color.BLACK));
//            return;
//        }
//
//        if (!userpasswordPatternCorrect()) {
//            txtPassword.setBorder(BorderFactory.createLineBorder(Color.RED));
//            jLabel3.setForeground(Color.red);
//            JOptionPane.showMessageDialog(null, "Password should contain 1 uppercase character, 1 lowercase character, 1 special character, 1 digit and should be of minimum length 6");
//            txtPassword.setBorder(BorderFactory.createLineBorder(Color.BLACK));
//            return;
//        }
//
//        if (rePwd == null || rePwd.equals("")) {
//            txtConfirmPass.setBorder(BorderFactory.createLineBorder(Color.RED));
//            jLabel4.setForeground(Color.red);
//            JOptionPane.showMessageDialog(null, "Confirm Password should match password");
//            txtConfirmPass.setBorder(BorderFactory.createLineBorder(Color.BLACK));
//            return;
//        }
//
//        if (!pwd.equals(rePwd)) {
//            confirmPasswordField.setBorder(BorderFactory.createLineBorder(Color.RED));
//            jLabel4.setForeground(Color.red);
//            JOptionPane.showMessageDialog(null, "Confirm Password should match password");
//            txtConfirmPass.setBorder(BorderFactory.createLineBorder(Color.BLACK));
//            return;
//        }

        if (btnGrp.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Please select a role");
            return;
        }

        if (btnAdmin.isSelected()) {
//            UserAccount admin = adminDirectory.createAgent();
//            admin.setName(txtName.getText());
//            admin.setUserName(username);
//            admin.setPassword(pwd);
//            admin.setRole("Travel Agent");
        }

        if (btnUser.isSelected()) {
//            Airliner airliner = airlinerDirectory.createAirliner();
//            airliner.setName(txtName.getText());
//            airliner.setUserName(username);
//            airliner.setPassword(pwd);
//            airliner.setRole("Airliner");
        }

        JOptionPane.showMessageDialog(null, "Account Created Successfully");
        rightContainer.remove(this);
        CardLayout leftLayout = (CardLayout) leftContainer.getLayout();
        UserLogin userLoginJPanel = new UserLogin(leftContainer, rightContainer, userAccountDirectory);
        leftContainer.add("UserLoginJPanel", userLoginJPanel);
        leftLayout.next(leftContainer);
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAdmin;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.ButtonGroup btnGrp;
    private javax.swing.JRadioButton btnUser;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
