/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Enterprise.Enterprise;
import Business.FundRaiserEvents.EventDirectory;
import Business.Role.AdminRole;
import Business.Role.BankEmployee;
import Business.Role.UserRole;
import Business.UserAccount.UserAccountDirectory;
import Business.UserAccount.UserAccount;
import UserInterface.AdminRole.AdminLeftJPanel;
import UserInterface.AdminRole.AdminWorkAreaJPanel;
import UserInterface.BankRole.BankDashBoardJPanel;
import UserInterface.BankRole.BankLeftJPanel;
import UserInterface.UserRole.UserHomeJPanel;
import UserInterface.UserRole.UserWorkAreaJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author @author Urvashi
 */
public class UserLogin extends javax.swing.JPanel {
    private JPanel leftContainer;
    private JPanel rightContainer;
    private UserAccountDirectory userAccountDirectory;
    private Enterprise enterprise;
    private EventDirectory eventdirectory;
    /**
     * Creates new form UserLogin
     */
    
    public UserLogin(JPanel leftContainer, JPanel rightContainer, UserAccountDirectory userAccountDirectory, 
            Enterprise enterprise, EventDirectory eventdirectory) {
        initComponents();
        this.leftContainer = leftContainer;
        this.rightContainer = rightContainer;
        this.userAccountDirectory = userAccountDirectory;
        //this.enterprise = enterprise;
        this.eventdirectory = eventdirectory;
    }
    
    public void setLoginFieldEnabled(){
    txtUserName.setEnabled(true);
    txtPassword.setEnabled(true);
    btnLogin.setEnabled(true);
    btnNewUSer.setEnabled(true);
    }
    
    public void setLoginFieldDisabled(){
        btnLogin.setEnabled(false);
        btnNewUSer.setEnabled(false);
        txtUserName.setEnabled(false);
        txtPassword.setEnabled(false);
    }
    
    private void refreshLeftContainer(){
        leftContainer.remove(this);
        CardLayout layout= (CardLayout) leftContainer.getLayout();
        layout.previous(leftContainer);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnNewUSer = new javax.swing.JButton();

        jLabel1.setText("User Name");

        jLabel2.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnNewUSer.setText("New User?");
        btnNewUSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUSerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNewUSer)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(btnNewUSer)
                .addContainerGap(212, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String userName = txtUserName.getText();
        char[] passwordCharArray = txtPassword.getPassword();
        String password = String.valueOf(passwordCharArray);
        boolean flag = false;
        UserAccount  userAccount = userAccountDirectory.authenticateUser(userName, password);
        if (userAccount != null) {
            if(userAccount.getRole().getClass().equals(AdminRole.class)){
            CardLayout leftLayout = (CardLayout) leftContainer.getLayout();
            leftContainer.add("AdminLeftJPanel", new AdminLeftJPanel());
            leftLayout.next(leftContainer);
            CardLayout rightLayout = (CardLayout) rightContainer.getLayout();
            rightContainer.add("AdminWorkAreaJPanel", new AdminWorkAreaJPanel(rightContainer, enterprise, eventdirectory));
            rightLayout.next(rightContainer);
            }
            else if(userAccount.getRole().getClass().equals(UserRole.class)) {
            CardLayout leftLayout = (CardLayout) leftContainer.getLayout();
            leftContainer.add("UserWorkAreaJPanel", new UserWorkAreaJPanel(leftContainer, rightContainer, userAccountDirectory, enterprise, eventdirectory));
            leftLayout.next(leftContainer);
            CardLayout rightLayout = (CardLayout) rightContainer.getLayout();
            rightContainer.add("UserHomeJPanel", new UserHomeJPanel(leftContainer, rightContainer, userAccountDirectory, enterprise, eventdirectory));
            rightLayout.next(rightContainer);
            }
            else if(userAccount.getRole().getClass().equals(BankEmployee.class)){
            CardLayout leftLayout = (CardLayout) leftContainer.getLayout();
            leftContainer.add("BankLeftJPanel", new BankLeftJPanel());
            leftLayout.next(leftContainer);
            CardLayout rightLayout = (CardLayout) rightContainer.getLayout();
            rightContainer.add("BankDashBoardJPanel", new BankDashBoardJPanel());
            rightLayout.next(rightContainer);
            }
            flag = true; 
        }
        if(!flag){
            JOptionPane.showMessageDialog(null, "Invalid UserName/Password");
            return;
        }
        setLoginFieldDisabled();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnNewUSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUSerActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        CreateNewUser createNewUser = new CreateNewUser(leftContainer, rightContainer, userAccountDirectory);
        rightContainer.add("CreateNewUser", createNewUser);
        layout.next(rightContainer);
        refreshLeftContainer();
    }//GEN-LAST:event_btnNewUSerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNewUSer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
