/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FundraisingEventEmployee;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.FundRaiserEvents.EventDirectory;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CreateEventByOrganizationEmployeeDirectory;
import Business.WorkRequest.CreateEventByOrganizationEmployee;
import Business.WorkRequest.VerificationRequest;
import Business.WorkRequest.WorkRequest;
import UserInterface.BankRole.BankDashBoardJPanel;
import UserInterface.BankRole.VerificationRequestJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MMI
 */
public class FundraisingEventsPendingRequests extends javax.swing.JPanel {

  private JPanel rightContainer;
       private EcoSystem system;
       private EventDirectory eventDirectory;
       private CreateEventByOrganizationEmployeeDirectory createEventByOrganizationEmployeeDirectory;
       private Enterprise enterprise;
    

    /**
     * Creates new form FundraisingEventsPendingRequests
     */
    public FundraisingEventsPendingRequests(JPanel rightContainer, EventDirectory eventdirectory,Enterprise enterprise) {
         initComponents();
         this.enterprise = enterprise;
         this.rightContainer = rightContainer;
         this.eventDirectory = eventdirectory;       
         this.createEventByOrganizationEmployeeDirectory = enterprise.getCreateEventByOrganizationEmployeeDirectory();
            
       
           populateTable();
    }

    private void populateTable() {
      DefaultTableModel model = (DefaultTableModel) tblPendingRequest.getModel();
        model.setRowCount(0);        
        for(CreateEventByOrganizationEmployee cs : createEventByOrganizationEmployeeDirectory.getCreateEventByOrganizationEmployeeList()){
                     
                    Object[] row = new Object[7];
                    row[0] = cs.getRequestID();
                    row[1] = cs.getTitle();
                    row[2] = cs.getDescription();
                    row[3] = cs.getSender();
                    row[4] = cs.getDeadline();
                    row[5] = cs.getLocation();
                    row[6] = ' ';
                    
                    model.addRow(row);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendingRequest = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnUserVerifReq = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();

        tblPendingRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Event Name", "Description", "Created By", "Date of Event", "Location", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPendingRequest);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pending Requests");

        btnUserVerifReq.setText("UserAccount Verification");
        btnUserVerifReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserVerifReqActionPerformed(evt);
            }
        });

        btnAssign.setText("Assign to me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUserVerifReq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAssign)
                                .addGap(4, 4, 4)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUserVerifReq)
                    .addComponent(btnAssign))
                .addGap(72, 72, 72))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
//        int selectedRow = tblPendingRequest.getSelectedRow();
//        if (selectedRow < 0) {
//            JOptionPane.showMessageDialog(null, "Please select a row from the table", "Warning", JOptionPane.WARNING_MESSAGE);
//        } else {
//            WorkRequest workrequest = (WorkRequest) tblPendingRequest.getValueAt(selectedRow, 0);
//            workrequest.setReceiver(useraccount);
//            JOptionPane.showMessageDialog(null, "Request Assigned");
//            btnAssign.setEnabled(false);
//        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnUserVerifReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserVerifReqActionPerformed
//        int selectedRow = tblPendingRequest.getSelectedRow();
//        if (selectedRow < 0) {
//            JOptionPane.showMessageDialog(null, "Please select a row from the table", "Warning", JOptionPane.WARNING_MESSAGE);
//        } else {
//            WorkRequest workRequest = (WorkRequest) tblPendingRequest.getValueAt(selectedRow, 0);
//            workRequest.setSender(useraccount);
//           // VerificationRequestJPanel verificationRequestJPanel = new VerificationRequestJPanel(rightContainer, useraccount, system);
//         //   rightContainer.add("VerificationRequestJPanel", verificationRequestJPanel);
//            CardLayout layout = (CardLayout) rightContainer.getLayout();
//            layout.next(rightContainer);
//        }   
    }//GEN-LAST:event_btnUserVerifReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnUserVerifReq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPendingRequest;
    // End of variables declaration//GEN-END:variables
}
