/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole;

import Business.Enterprise.Enterprise;
import Business.FundRaiserEvents.EventDirectory;
import Business.UserAccount.UserAccountDirectory;
import UserInterface.UserLogin;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author @author Urvashi
 */
public class AdminLeftJPanel extends javax.swing.JPanel {

    private JPanel leftContainer;
    private JPanel rightContainer;
    private UserAccountDirectory userAccountDirectory; 
    private Enterprise enterprise; 
    private EventDirectory eventdirectory;
    
    /**
     * Creates new form AdminLeftJPanel
     */
    public AdminLeftJPanel(JPanel leftContainer, JPanel rightContainer, UserAccountDirectory userAccountDirectory,
            Enterprise enterprise, EventDirectory eventdirectory) {
        initComponents();
        this.leftContainer = leftContainer;
        this.rightContainer= rightContainer;
        this.userAccountDirectory = userAccountDirectory;
        this.enterprise = enterprise;
        this.eventdirectory = eventdirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHome = new javax.swing.JButton();
        btnPendingApprovals = new javax.swing.JButton();
        btnWithdrawalReq = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnPendingApprovals.setText("Pending Approvals");
        btnPendingApprovals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendingApprovalsActionPerformed(evt);
            }
        });

        btnWithdrawalReq.setText("Withdrawal Request");

        btnLogOut.setText("Logout");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWithdrawalReq)
                    .addComponent(btnPendingApprovals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnHome)
                .addGap(53, 53, 53)
                .addComponent(btnPendingApprovals)
                .addGap(44, 44, 44)
                .addComponent(btnWithdrawalReq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(130, 130, 130))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        rightContainer.remove(this);
        CardLayout rightLayout = (CardLayout) rightContainer.getLayout();
        rightContainer.add("AdminWorkAreaJPanel", new AdminWorkAreaJPanel(rightContainer, enterprise, eventdirectory));
        rightLayout.next(rightContainer);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnPendingApprovalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendingApprovalsActionPerformed
        rightContainer.remove(this);
        CardLayout rightLayout = (CardLayout) rightContainer.getLayout();
        rightContainer.add("AdminPendingApprovalJPanel", new AdminPendingApprovalJPanel());
        rightLayout.next(rightContainer);
    }//GEN-LAST:event_btnPendingApprovalsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        leftContainer.remove(this);
        CardLayout leftCardLayout = (CardLayout) leftContainer.getLayout();
        leftContainer.add("UserLogin", new UserLogin(leftContainer, rightContainer, userAccountDirectory, enterprise, eventdirectory));
        leftCardLayout.next(leftContainer);
        Component [] components = rightContainer.getComponents();
        for(Component c : components){
        rightContainer.remove(c);        
        }
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPendingApprovals;
    private javax.swing.JButton btnWithdrawalReq;
    // End of variables declaration//GEN-END:variables
}
